title = "tivasyk.blog"
baseURL = "https://tivasyk.github.io"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "uk-UA"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "tivasyk-blog"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Description and meta data for the search engines
  author = "tivasyk"
  description = "tivasyk personal blog on life, universe and everything"
  keywords = "tivasyk,blog,personal,ukraine,linux"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable algolia search
  algolia_search    = false
  algolia_appId     = "Y2C4RWMPXW"
  algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
  algolia_indexName = "default-content"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "життя, всесвіт і все інше"

    # if you want to use gravatar for the header image
    gravatarEMail = "tivasyk@gmail.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  facebook   = "https://facebook.com/tivasyk"
  twitter    = "https://twitter.com/tivasyk"
  googleplus = "https://plus.google.com/tivasyk"
  pinterest  = ""
  instagram  = "https://instagram.com/tivasyk"
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/tivasyk"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
